name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/StoreOps/StoreOps.csproj

    - name: Build
      run: dotnet build ./src/StoreOps/StoreOps.csproj --configuration Release

    - name: Test
      run: echo "Sem testes"

    - name: Publish
      run: dotnet publish ./src/StoreOps/StoreOps.csproj --configuration Release --output ./out
